#!/usr/bin/env bash

Version="chainz 1.0.2 (Minor Update)
Chainz: Blue Fish"
cmd="$1"
pkg="$2"

#Notes Script
if [[ "$cmd" == "-N" ]]; then
	echo "=== Chainz Notes ==="
	echo "Fixed missing space in -R function of 'help'"
	echo "Moved around the 'help' page to be more ascetically pleasing"
	echo "Added --help to print 'help'"
	echo "When not running any functions will upgrade"
	exit 0
fi

#Version Script
if [[ "$cmd" == "--version" ]]; then
	echo "$Version"
	exit 0 
fi

#Help Script
if [[ "$cmd" == "-H" || "$cmd" == "--help" ]]; then
	echo "Chainz $Version"
	echo "chainz --version      --> Prints Version"
	echo "chainz --help         --> Prints Help"
	echo "chainz -I {Package}   --> Installs Packages"
	echo "chainz -IY {Package}  --> Installs yay Packages"
	echo "chainz -R {Package}   --> Removes Packages"
	echo "chainz -N             --> Prints Chainz Update Notes"
	echo "chainz -U             --> Upgrades System"
	exit 0
fi

#Upgrade Script
if [[ -z "$cmd" || "$cmd" == "-U" ]]; then
    echo "=== Chainz Full System Upgrade ==="
    echo
    echo "===     Upgrading Packages     ==="
    yay -Syu --noconfirm
    echo
    echo "===    System Upgrade Done     ==="
fi

#Remove Script
if [[ "$cmd" == "-R" ]]; then
	if [[ -z "$pkg"	]];  then
		echo "Error: No package specified."
		echo "Usage: chainz -R {package}"
		exit 0
	fi

	echo "===      Removing Package      ==="
	yay -R "$pkg" --noconfirm
	echo "===      Package Removed       ==="
fi

#Install Pacman Script
if [[ "$cmd" == "-I" ]]; then
	if [[ -z "$pkg" ]]; then
		echo "Error: No package specified."
		echo "Usage: chainz -I {package}"
		exit 0
	fi
	echo "===   Chainz Package Install   ==="
	if ! sudo pacman -S "$pkg" --noconfirm; then
	echo "Failed to install '$pkg' with Pacman"
	exit 0
	fi
	echo "===     Package Installed      ==="
fi

#Instal Yay Script
if [[ "$cmd" == "-IY" ]]; then
	if [[ -z "$pkg" ]]; then
		echo "Error: No package specified."
		echo "Usage:chainz -IY {package}"
		exit 0
	fi
	echo "=== Chainz Yay Package Install ==="
	if ! yay -S "$pkg" --noconfirm; then
		echo "Failed to install '$pkg' with Yay"
		exit 0
		fi
		echo "=== Yay Package Installed ==="
		exit 0
fi
