#!/usr/bin/env bash

Version="Chainz-PKG 1.1.0 (Minor/Developer Update)
Chainz: Red Bar"

cmd="$1"
pkg="$2"

case "$cmd" in

    -N)
        echo "=== Chainz Notes ==="
        echo "Updated to 'case' instead of 'if' statements"
        echo "Added -V flag to print version"
        echo "Made 'help' more readable"
        exit 0
        ;;

    --version|-V)
        echo "$Version"
        exit 0
        ;;

    -H|--help)
        echo "Chainz $Version"
        echo "chainz --version | -V --> Prints Version"
        echo "chainz --help | -H    --> Prints Help"
        echo "chainz -I {Package}   --> Installs Packages"
        echo "chainz -IY {Package}  --> Installs yay Packages"
        echo "chainz -R {Package}   --> Removes Packages"
        echo "chainz -N             --> Prints Chainz Update Notes"
        echo "chainz -U             --> Upgrades System"
        exit 0
        ;;

    -U|"")
        echo "=== Chainz Full System Upgrade ==="
        echo
        echo "===     Upgrading Packages     ==="
        yay -Syu --noconfirm
        echo
        echo "===    System Upgrade Done     ==="
        exit 0
        ;;

    -R)
        if [[ -z "$pkg" ]]; then
            echo "Error: No package specified."
            echo "Usage: chainz -R {package}"
            exit 1
        fi

        echo "===      Removing Package      ==="
        yay -R "$pkg" --noconfirm
        echo "===      Package Removed       ==="
        exit 0
        ;;

    -I)
        if [[ -z "$pkg" ]]; then
            echo "Error: No package specified."
            echo "Usage: chainz -I {package}"
            exit 1
        fi

        echo "===   Chainz Package Install   ==="
        if ! sudo pacman -S "$pkg" --noconfirm; then
            echo "Failed to install '$pkg' with Pacman"
            exit 1
        fi
        echo "===     Package Installed      ==="
        exit 0
        ;;

    -IY)
        if [[ -z "$pkg" ]]; then
            echo "Error: No package specified."
            echo "Usage: chainz -IY {package}"
            exit 1
        fi

        echo "=== Chainz Yay Package Install ==="
        if ! yay -S "$pkg" --noconfirm; then
            echo "Failed to install '$pkg' with Yay"
            exit 1
        fi
        echo "=== Yay Package Installed ==="
        exit 0
        ;;

    *)
        echo "Unknown option: $cmd"
        echo "Run 'chainz --help' for usage."
        exit 1
        ;;
esac
