#!/usr/bin/env bash

Version="
Chainz-PKG 1.2.0 (Major Update)
Chainz: Red Metal
"

cmd="$1"
pkg="$2"

case "$cmd" in

    --notes|-N)
        echo "=== Chainz Notes ==="
        echo "Added full flatpak support"
	echo "Added 'future' flag"
	echo "added '--notes' flag to print notes"
        exit 0
        ;;

    --version|-V)
        echo "$Version"
        exit 0
        ;;

    --future|-F)
        echo "=== Chainz Future ==="
        echo "Full search support for flatpak, pacman and yay"
	echo "Search for all package managers"
	echo "Interactive mode"
        exit 0
        ;;

    --help|-H)
        echo "Chainz $Version"
        echo "chainz --version | -V --> Prints Version"
        echo "chainz --help | -H    --> Prints Help"
        echo "chainz --future | -F  --> Prints the next chainz update"
        echo "chainz --notes | -N   --> Prints Chainz Update Notes"
        echo "chainz -I {Package}   --> Installs Packages"
        echo "chainz -IY {Package}  --> Installs yay Packages"
        echo "chainz -IF {package}  --> Installs Flatpak Packages"
        echo "chainz -RF {package}  --> Removes Flatpak Packages"
        echo "chainz -R {Package}   --> Removes Packages"
        echo "chainz -U             --> Upgrades System"
        exit 0
        ;;

    -U|"")
        echo "=== Chainz Full System Upgrade ==="
        echo
        echo "===     Upgrading Packages     ==="
        yay -Syu --noconfirm
       echo
        echo "===    System Upgrade Done     ==="
        exit 0
        ;;

    -R)
        if [[ -z "$pkg" ]]; then
            echo "Error: No package specified."
            echo "Usage: chainz -R {package}"
            exit 1
        fi

        echo "===      Removing Package      ==="
        yay -R "$pkg" --noconfirm
        echo "===      Package Removed       ==="
        exit 0
        ;;

    -RF)
        if [[ -z "$pkg" ]]; then
            echo "Error: No package specified."
            echo "Usage: chainz -RF {package}"
            exit 1
        fi

        echo "===  Removing Flatpak Package  ==="
        flatpak remove -y "$pkg"
        echo "===   Flatpak Package Removed  ==="
        exit 0
        ;;

    -I)
        if [[ -z "$pkg" ]]; then
            echo "Error: No package specified."
            echo "Usage: chainz -I {package}"
            exit 1
        fi

        echo "===   Chainz Package Install   ==="
        if ! sudo pacman -S "$pkg" --noconfirm; then
            echo "Failed to install '$pkg' with Pacman"
            exit 1
        fi
        echo "===     Package Installed      ==="
        exit 0
        ;;

    -IY)
        if [[ -z "$pkg" ]]; then
            echo "Error: No package specified."
            echo "Usage: chainz -IY {package}"
            exit 1
        fi

        echo "=== Chainz Yay Package Install ==="
        if ! yay -S "$pkg" --noconfirm; then
            echo "Failed to install '$pkg' with Yay"
            exit 1
        fi
        echo "===   Yay Package Installed    ==="
        exit 0
        ;;
    -IF)
        if [[ -z "$pkg" ]]; then
        echo "Error: No package specified."
        echo "Usage: chainz -IF {package}"
        exit 1
        fi

        echo "===   Chainz Flatpak Install   ==="
        if ! flatpak install -y "$pkg"; then
        echo "Failed to install '$pkg' with Flatpak"
        exit 1
        fi

        echo "=== Flatpak Package Installed  ==="
        exit 0
        ;;

    *)
        echo "Unknown option: $cmd"
        echo "Run 'chainz --help' for usage."
        exit 1
        ;;
esac
